### ISSUE TITLE
Mcrypt PHP extension required

### ISSUE THREAD

**Issue by cleechtech** [csoutham/laravel-todo-app#1]
I am following the instructions but run into this error:

```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
> php artisan clear-compiled
Mcrypt PHP extension required.
Script php artisan clear-compiled handling the post-update-cmd event returned with an error


                      
  [RuntimeException]  
  Error Output:       
                      


update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--] [<packages>]...
```

Here are my version numbers:

```
$ laravel --version
Laravel Installer version 1.3.1
$ php --version
PHP 5.5.30 (cli) (built: Oct 23 2015 17:21:45)
```

**Comment by hedegaard** [comment]
Are you not just missing the mcrypt php module? (remember you also have to enable it php5enmod mcrypt)

**Comment by cleechtech** [comment]
Excuse me, what does that mean? I did `git clone <this_repo>` then `composer update`. Clearly I am missing something!

**Comment by hedegaard** [comment]
this might be what you need?

http://coolestguidesontheplanet.com/install-mcrypt-for-php-on-mac-osx-10-10-yosemite-for-a-development-server/

**Comment by cleechtech** [comment]
hmmmm I hoped that `brew install homebrew/php/php55-mcrypt` as per [this SO post](http://stackoverflow.com/a/20039833/2031033) would fix it, but it does not. I do not have MAMP or XAMP installed on my mac. Maybe that's an issue?

**Comment by hedegaard** [comment]
It will not matter how you install it, or if you have mamp or xamp as long as it works. But I really do not think this is a project related bug but your configuration instead.

**Comment by cleechtech** [comment]
Yeah it's something I need to work out with my own configuration. Laravel is the trickiest getting started framework I have worked with so far.
